-- ============================================================================
-- Seed products from the paper KITCHEN CONSUMPTION REPORT.
--
-- 286 rows. Every product goes in with status='active' and NO
-- opening stock, no incoming batch, and no outgoing entry — the point is
-- to have every product's row present on every future report/calendar
-- BEFORE any stock arrives. Quantity columns will show blank/zero until a
-- real incoming batch is recorded through the app.
--
-- On conflict (a product with the same normalized name already exists —
-- e.g. the operator already added it manually) the seed only fills in the
-- category if the existing row has none, and never overwrites unit or
-- status. Safe to re-run.
-- ============================================================================

with seed(name, unit, category_name) as (
  values
  ('Sugar', 'KG', 'General & Grains'),
  ('Salt (800gm)', 'KG', 'General & Grains'),
  ('White Pepper Powder', 'KG', 'Spices & Seasonings'),
  ('Black Pepper Powder', 'KG', 'Spices & Seasonings'),
  ('Kachri Powder', 'KG', 'Spices & Seasonings'),
  ('Dry Oregano (500gm)', 'KG', 'Spices & Seasonings'),
  ('Dry Thyme (500gm)', 'KG', 'Spices & Seasonings'),
  ('Dry Tarragon (500gm)', 'KG', 'Spices & Seasonings'),
  ('Dry Rosemary (500gm)', 'KG', 'Spices & Seasonings'),
  ('Eka powder (500gm)', 'KG', 'Spices & Seasonings'),
  ('Yeast (500gm)', 'KG', 'Baking & Confectionery'),
  ('Soy Sauce (5 ltr)', 'Liter', 'Sauces & Condiments'),
  ('Corn Flour', 'KG', 'General & Grains'),
  ('Flour', 'KG', 'General & Grains'),
  ('Semolina Suji', 'KG', 'General & Grains'),
  ('Pizza Flour', 'KG', 'General & Grains'),
  ('Chicken Powder (1kg)', 'KG', 'Spices & Seasonings'),
  ('Milk Pack Cream (200gm)', 'Liter', 'Dairy, Cheese & Eggs'),
  ('Tomato Paste (800gm)', 'KG', 'General & Grains'),
  ('Nurpur Butter Yellow', 'KG', 'Dairy, Cheese & Eggs'),
  ('Yellow Butter Adams', 'KG', 'Dairy, Cheese & Eggs'),
  ('Cheddar Cheese (2kg)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Mozzarella Cheese (2kg)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Tomato Ketchup (4kg)', 'KG', 'Sauces & Condiments'),
  ('Mayonnaise     (4kg)', 'KG', 'Sauces & Condiments'),
  ('Chili Garlic Ketchup (4kg)', 'KG', 'Sauces & Condiments'),
  ('Mushroom 2.5kg (1200 g)', 'KG', 'Canned & Preserved'),
  ('Green Olive 3 kg (1200 g)', 'Gram', 'Canned & Preserved'),
  ('Black Olive  2.5 kg (1200 g)', 'Gram', 'Canned & Preserved'),
  ('Jalapeno Tin 3kg', 'KG', 'Canned & Preserved'),
  ('Jalapeno (1500 gm)', 'Gram', 'Canned & Preserved'),
  ('Sweet Corn        (1kg)', 'KG', 'Canned & Preserved'),
  ('Egg', 'Piece', 'Dairy, Cheese & Eggs'),
  ('Cheese Slice White', 'KG', 'Dairy, Cheese & Eggs'),
  ('Cheese Slice Yellow', 'KG', 'Dairy, Cheese & Eggs'),
  ('Bread Crumb', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Baked Beans (400gm)', 'KG', 'Canned & Preserved'),
  ('Everyday Dry Milk (850 gm)', 'KG', 'Dairy, Cheese & Eggs'),
  ('MILK', 'Liter', 'Dairy, Cheese & Eggs'),
  ('Lime Seasoning (400 gm)', 'KG', 'Spices & Seasonings'),
  ('Nurpur Butter Dip 10 g (100 pc)', 'Piece', 'Dairy, Cheese & Eggs'),
  ('Apple Jam Dip  (1.5kg)', 'Piece', 'Preserves & Jams'),
  ('Sundriad Tomato(180gm)', 'KG', 'Preserves & Jams'),
  ('Mezan Oil (16ltr)', 'Liter', 'Sauces & Condiments'),
  ('Fettuccini Pasta (500gm)', 'KG', 'General & Grains'),
  ('Clying Film 14''''', 'Roll', 'Packaging & Disposables'),
  ('Feta Cheese (500gm)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Clying Film 18''''', 'Roll', 'Packaging & Disposables'),
  ('Strawberry Jam', 'KG', 'Preserves & Jams'),
  ('Worcastershire Sauce (750ml)', 'ML', 'Sauces & Condiments'),
  ('Food Color Yellow', 'Gram', 'Baking & Confectionery'),
  ('Food Color Green', 'Gram', 'Baking & Confectionery'),
  ('Food Color Red', 'Gram', 'Baking & Confectionery'),
  ('Haleeb Cream    (200ml)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Kitchen Gloves Black', 'Piece', 'Packaging & Disposables'),
  ('Vinyl Gloves', 'KG', 'Packaging & Disposables'),
  ('Net Cape (100piece)', 'Piece', 'Packaging & Disposables'),
  ('Towel Duster', 'KG', 'Packaging & Disposables'),
  ('PE Gloves', 'KG', 'Packaging & Disposables'),
  ('Whip Cream 1 kg', 'Liter', 'Dairy, Cheese & Eggs'),
  ('Brown Sugar', 'KG', 'Baking & Confectionery'),
  ('Cocoa Powder', 'KG', 'Baking & Confectionery'),
  ('G.P White Chocolate', 'KG', 'Baking & Confectionery'),
  ('G.P Dark Chocolate', 'KG', 'Baking & Confectionery'),
  ('Cherry', 'Gram', 'Fruits'),
  ('Chocolate Chip (1kg)', 'KG', 'Baking & Confectionery'),
  ('Chocolate Chip White (1kg)', 'KG', 'Baking & Confectionery'),
  ('Condense Milk (1kg)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Strawberry Filling (595gm)', 'KG', 'Baking & Confectionery'),
  ('Nurpur Butter White (1kg)', 'KG', 'Dairy, Cheese & Eggs'),
  ('Cinnamon Powder', 'Gram', 'Spices & Seasonings'),
  ('Baking Soda (100g)', 'Gram', 'Baking & Confectionery'),
  ('Walnut', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Raisin', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Wrapping Roll', 'Roll', 'Packaging & Disposables'),
  ('Yogurt', 'KG', 'Dairy, Cheese & Eggs'),
  ('Icing Sugar (900 gm)', 'Gram', 'Baking & Confectionery'),
  ('Kitchen Tissue Roll (Small)', 'Roll', 'Packaging & Disposables'),
  ('Kitchen Tissue Roll (Large)', 'Roll', 'Packaging & Disposables'),
  ('Penne Pasta (500gm)', 'Gram', 'General & Grains'),
  ('Elbow Pasta (400gm)', 'Gram', 'General & Grains'),
  ('Red Wine Vinegar (500ml)', 'ML', 'Sauces & Condiments'),
  ('Baby Corn (170gm)', 'Gram', 'Canned & Preserved'),
  ('Parmesan Cheese', 'KG', 'Dairy, Cheese & Eggs'),
  ('Fruit Cocktail (1829 g)', 'Gram', 'Baking & Confectionery'),
  ('Sufi Cooking Oil  (16ltr)', 'Liter', 'Sauces & Condiments'),
  ('Yellow Mustard (227gm)', 'Gram', 'Sauces & Condiments'),
  ('Vinegar Local (3 ltr)', 'ML', 'Sauces & Condiments'),
  ('Aluminium Foil', 'KG', 'Packaging & Disposables'),
  ('Chicken Stock Cubes Knorr', 'KG', 'Spices & Seasonings'),
  ('M.R.D Tags Roll', 'Roll', 'Packaging & Disposables'),
  ('Honey (1kg)', 'KG', 'Preserves & Jams'),
  ('White Chickpeas', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Red Beans', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Tabasco (60ml)', 'ML', 'Sauces & Condiments'),
  ('Daal Masoor', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Tea', 'KG', 'Beverages'),
  ('Mango Jam', 'KG', 'Preserves & Jams'),
  ('Chocolate Syrup (623 ml)', 'Liter', 'Baking & Confectionery'),
  ('Strawberry Syrup (623 ml)', 'KG', 'Baking & Confectionery'),
  ('Maple Syrup 710 ml', 'ML', 'Baking & Confectionery'),
  ('Black Pepper Whole', 'Gram', 'Spices & Seasonings'),
  ('Rice Flour', 'Gram', 'General & Grains'),
  ('Batter Mix', 'KG', 'General & Grains'),
  ('Garam Flour', 'Gram', 'Spices & Seasonings'),
  ('Garlic Powder', 'Gram', 'Spices & Seasonings'),
  ('Dijon Mustard (370 gm )', 'Gram', 'Sauces & Condiments'),
  ('Tikka Masala', 'Gram', 'Spices & Seasonings'),
  ('Baking Powder (4.5kg)', 'Gram', 'Baking & Confectionery'),
  ('Chili Sauce (5 ltr)', 'Liter', 'Sauces & Condiments'),
  ('sweet chilli sauce botle', 'KG', 'Sauces & Condiments'),
  ('Red Crush Chili', 'Gram', 'Spices & Seasonings'),
  ('Vanilla Essence (450ml)', 'ML', 'Baking & Confectionery'),
  ('B.B.Q Sauce (200gm)', 'Gram', 'Sauces & Condiments'),
  ('Dark Soya Sauce (500ml)', 'ML', 'Sauces & Condiments'),
  ('light soya sauce', 'KG', 'Sauces & Condiments'),
  ('Choclate Sprinkles (1kg)', 'KG', 'Baking & Confectionery'),
  ('Multi Sprinkles (1kg)', 'Gram', 'Baking & Confectionery'),
  ('Siracha Sauce (510gm)', 'KG', 'Sauces & Condiments'),
  ('Chat Masala (1kg)', 'KG', 'Spices & Seasonings'),
  ('Turmeric Powder (1kg)', 'Gram', 'Spices & Seasonings'),
  ('Corriander Powder (1kg)', 'Gram', 'Spices & Seasonings'),
  ('Cumin Powder', 'KG', 'Spices & Seasonings'),
  ('Soy Sauce (Kikoman)', 'ML', 'Sauces & Condiments'),
  ('Red Chili Powder', 'Gram', 'Spices & Seasonings'),
  ('Cumin Whole', 'KG', 'Spices & Seasonings'),
  ('Green Cardamon', 'KG', 'Spices & Seasonings'),
  ('Bay Leaf', 'KG', 'Spices & Seasonings'),
  ('Black Cardamom', 'KG', 'Spices & Seasonings'),
  ('Star Anise', 'KG', 'Spices & Seasonings'),
  ('Clove', 'Gram', 'Spices & Seasonings'),
  ('Fish Sauce (750ml) New', 'KG', 'Meat & Poultry'),
  ('Achar Masala', 'KG', 'Spices & Seasonings'),
  ('Kewra Water (200ml)', 'ML', 'Spices & Seasonings'),
  ('Poppy Seed', 'KG', 'Spices & Seasonings'),
  ('Whole Spice Powder', 'KG', 'Spices & Seasonings'),
  ('Blueberry Syrup (623ml)', 'KG', 'Baking & Confectionery'),
  ('Blueberry Filling (595gm)', 'KG', 'Baking & Confectionery'),
  ('Caramel Syrup (623ml)', 'ML', 'Baking & Confectionery'),
  ('Puck Cheese (500 gm)', 'Gram', 'Dairy, Cheese & Eggs'),
  ('Butter Paper', 'Gram', 'Packaging & Disposables'),
  ('Adam Mix Cheese', 'Gram', 'Dairy, Cheese & Eggs'),
  ('Caster Sugar', 'KG', 'Baking & Confectionery'),
  ('Granulated Sugar', 'Gram', 'Baking & Confectionery'),
  ('Red Colour Liquid (110ml)', 'KG', 'Baking & Confectionery'),
  ('Orange Colour Liquid', 'ML', 'Baking & Confectionery'),
  ('Pink Color Liquid', 'KG', 'Baking & Confectionery'),
  ('Yellow Colour Liquid (110ml)', 'KG', 'Baking & Confectionery'),
  ('Green Colour Liquid (110ml)', 'KG', 'Baking & Confectionery'),
  ('Blue Colour Liquid', 'ML', 'Baking & Confectionery'),
  ('Kidney Beans (400 gm)', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Choco Bliss', 'KG', 'Baking & Confectionery'),
  ('Glucose Liquid', 'KG', 'Baking & Confectionery'),
  ('Fruit Gel  (5kg)', 'KG', 'Preserves & Jams'),
  ('Lotus paste (Hoisin Sauce) (435 ml)', 'KG', 'Sauces & Condiments'),
  ('Dairy Milk Chocolate', 'KG', 'Dairy, Cheese & Eggs'),
  ('Sooper Biscuits', 'Box', 'Baking & Confectionery'),
  ('Marie Biscuts', 'KG', 'General & Grains'),
  ('Gelatin (50 G)', 'Gram', 'Baking & Confectionery'),
  ('Pumpkin Preserve', 'KG', 'Preserves & Jams'),
  ('Cane Sugar White', 'KG', 'Baking & Confectionery'),
  ('Four Seed', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Flex Seed', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Almond', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Pineapple Slice (1790gm)', 'Gram', 'Canned & Preserved'),
  ('Waffle Stick Box', 'KG', 'Packaging & Disposables'),
  ('Bran', 'KG', 'General & Grains'),
  ('Wheat flour', 'KG', 'General & Grains'),
  ('Black Sesame', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Black Mushroom', 'Gram', 'Canned & Preserved'),
  ('Mama Sita Oyster Sauce(2.27 ltr)', 'ML', 'Sauces & Condiments'),
  ('Muffin Casing', 'KG', 'Packaging & Disposables'),
  ('Mousse Glass', 'Piece', 'Packaging & Disposables'),
  ('Samolina', 'Gram', 'General & Grains'),
  ('Fish Cracker (100gm)', 'Gram', 'Meat & Poultry'),
  ('Tooth Pick (100 piece Box)', 'Piece', 'Packaging & Disposables'),
  ('Sesame Seed', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Piping Bags (100piece)', 'Gram', 'Packaging & Disposables'),
  ('Corriander Whole', 'KG', 'Spices & Seasonings'),
  ('Pakori', 'KG', 'Spices & Seasonings'),
  ('Black Vinegar (1300ml) New', 'Liter', 'Sauces & Condiments'),
  ('White Chocolate Slab', 'KG', 'Baking & Confectionery'),
  ('Coconut Crush', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Pistachio', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Chili paste botal', 'KG', 'Sauces & Condiments'),
  ('Khoya', 'Gram', 'Dairy, Cheese & Eggs'),
  ('Dry Mango Powder', 'KG', 'Spices & Seasonings'),
  ('Sambolic Sauce (250 gm)', 'Gram', 'Sauces & Condiments'),
  ('Appricot New', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Peanut New', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Mango Jelly (80gm)', 'KG', 'Preserves & Jams'),
  ('Strawberry Jelly (80 gm)', 'KG', 'Preserves & Jams'),
  ('Banana Jelly (80 gm)', 'KG', 'Preserves & Jams'),
  ('Vanilla Custard (275 gm)', 'KG', 'Baking & Confectionery'),
  ('Shezan Ketchup (5 kg)', 'Gram', 'Sauces & Condiments'),
  ('Sesame Oil', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Roll Patti (400 gm) New', 'KG', 'Frozen & Prepared'),
  ('Samosa Patti', 'KG', 'Frozen & Prepared'),
  ('MatchSticks', 'Box', 'Packaging & Disposables'),
  ('Peprika Powder ( 25 gm )', 'Gram', 'Spices & Seasonings'),
  ('Chicken Samosa', 'KG', 'Meat & Poultry'),
  ('Chicken Spring Roll', 'Box', 'Meat & Poultry'),
  ('Basmati Rice', 'KG', 'General & Grains'),
  ('Chandi Wark (12 Piece)', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('imli (Tamarind)', 'Gram', 'Sauces & Condiments'),
  ('Qorma Masala', 'Gram', 'Spices & Seasonings'),
  ('Biryani Masala', 'Gram', 'Spices & Seasonings'),
  ('English Newspaper', 'KG', 'Packaging & Disposables'),
  ('White Butter (unsalted) NurPur', 'KG', 'Dairy, Cheese & Eggs'),
  ('White Butter ( Local )', 'KG', 'Dairy, Cheese & Eggs'),
  ('Daal Chana', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Bhaly', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Bhaliya', 'KG', 'Dry Goods, Nuts & Legumes'),
  ('Lotus Paste (400 gm)', 'KG', 'Sauces & Condiments'),
  ('Prema Cream Cheese', 'KG', 'Dairy, Cheese & Eggs'),
  ('Lotus Biscuits (250 gm)', 'KG', 'Baking & Confectionery'),
  ('Dry plum', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Dry Apricot', 'Gram', 'Dry Goods, Nuts & Legumes'),
  ('Oreo Biscuits', 'KG', 'Baking & Confectionery'),
  ('Candy Biscuits', 'KG', 'Baking & Confectionery'),
  ('Kashmiri Tea', 'Gram', 'Beverages'),
  ('Strawberry Essence (25ml)', 'KG', 'Baking & Confectionery'),
  ('Puck Cream Cheese 500g', 'KG', 'Dairy, Cheese & Eggs'),
  ('Dalda Ghee', 'KG', 'Dairy, Cheese & Eggs'),
  ('Green Chili (HARI Mirch)', 'KG', 'Vegetables'),
  ('Tomato', 'KG', 'Vegetables'),
  ('Parsley', 'KG', 'Vegetables'),
  ('Lettuce Leaves', 'KG', 'Vegetables'),
  ('Potato', 'KG', 'Vegetables'),
  ('Corriander', 'KG', 'Vegetables'),
  ('Onion', 'KG', 'Vegetables'),
  ('Fresh Beans', 'KG', 'Vegetables'),
  ('Red Cabbage', 'KG', 'Vegetables'),
  ('Capsicum', 'KG', 'Vegetables'),
  ('Garlic', 'KG', 'Vegetables'),
  ('Ginger', 'KG', 'Vegetables'),
  ('Carrot', 'KG', 'Vegetables'),
  ('Ice Burg', 'KG', 'Vegetables'),
  ('Mint', 'KG', 'Vegetables'),
  ('Pomegranate', 'KG', 'Fruits'),
  ('Apple', 'KG', 'Fruits'),
  ('Chinese Cabbage', 'KG', 'Vegetables'),
  ('Fresh Basil', 'KG', 'Vegetables'),
  ('Lemon', 'KG', 'Fruits'),
  ('Cucumber', 'KG', 'Vegetables'),
  ('Beet Root', 'KG', 'Vegetables'),
  ('Broccoli', 'KG', 'Vegetables'),
  ('Spinach', 'KG', 'Vegetables'),
  ('Kivi', 'KG', 'Fruits'),
  ('Guava', 'KG', 'Fruits'),
  ('Cabbage', 'KG', 'Vegetables'),
  ('Strawberry', 'KG', 'Fruits'),
  ('Multi Capsicum', 'KG', 'Vegetables'),
  ('Banana', 'KG', 'Fruits'),
  ('Leek', 'KG', 'Vegetables'),
  ('Green Peas', 'KG', 'Vegetables'),
  ('Caulifower', 'KG', 'Vegetables'),
  ('Spring Onion', 'KG', 'Vegetables'),
  ('Scotch Bright Spunch', 'Piece', 'Cleaning & Dishwashing'),
  ('Bonus Surf', 'KG', 'Cleaning & Dishwashing'),
  ('Dishwashing Liquid', 'Liter', 'Cleaning & Dishwashing'),
  ('Lemon Mex Long bar ( Single )', 'KG', 'Cleaning & Dishwashing'),
  ('Steel Wool', 'Piece', 'Cleaning & Dishwashing'),
  ('Brush & Scraper', 'KG', 'Cleaning & Dishwashing'),
  ('Mortein Spray (375 ml)', 'KG', 'Cleaning & Dishwashing'),
  ('Insect killer Powder (125 ml)', 'KG', 'Cleaning & Dishwashing'),
  ('Long Brush', 'KG', 'Cleaning & Dishwashing'),
  ('Wiper', 'KG', 'Cleaning & Dishwashing'),
  ('White Bread  (17slice)', 'KG', 'Bread'),
  ('Brawn Bread (17slice)', 'KG', 'Bread'),
  ('Bran Bread (10slice)', 'KG', 'Bread'),
  ('Tortilla Bread (8 piece)', 'Piece', 'Bread'),
  ('Burger Bun (Home Made)', 'KG', 'Bread'),
  ('Brioch Bread  (Home Made)', 'KG', 'Bread'),
  ('Focaccia Bread  (Home Made)', 'KG', 'Bread'),
  ('Chicken Breast', 'KG', 'Meat & Poultry'),
  ('Chicken Wings', 'KG', 'Meat & Poultry'),
  ('Chicken Thigh Mince', 'KG', 'Meat & Poultry'),
  ('Beef Undercut Mince', 'KG', 'Meat & Poultry'),
  ('Chicken Sausages   (300 gm )', 'KG', 'Meat & Poultry'),
  ('Chicken Thigh Boneless', 'KG', 'Meat & Poultry'),
  ('Chicken Nuggets (1 kg)', 'KG', 'Meat & Poultry'),
  ('Mutton Fat', 'KG', 'Meat & Poultry'),
  ('Prawns', 'KG', 'Meat & Poultry'),
  ('Chicken Karahi Cut', 'KG', 'Meat & Poultry'),
  ('Fish (10kg)', 'KG', 'Meat & Poultry')
),
resolved as (
  select s.name, s.unit, c.id as category_id
  from seed s
  left join categories c on c.normalized_name = lower(trim(s.category_name))
)
insert into products (name, unit, category_id)
select r.name, r.unit, r.category_id
from resolved r
on conflict (normalized_name) do update
  set category_id = coalesce(products.category_id, excluded.category_id);
